modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''${mod_description}'''
logoFile = "${logo_file}"
license = "${mod_license}"

[[dependencies.vs_sup_fix]]
modId = "forge"
mandatory = true
versionRange = "[${forge_major_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_sup_fix]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_sup_fix]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_sup_fix]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[0,)""
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_sup_fix]]
modId = "supplementaries"
mandatory = true
versionRange = "[0,)""
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_sup_fix]]
modId = "moonlight"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_sup_fix]]
modId = "eureka"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"